;(function (root) {
  const SYNONYM_DATA = [
    { id: "cam10-t1p2-12-improve", source: "Cambridge 10 | T1-P2 12", prompt: "improve", answer: "refurbish" },
    { id: "cam10-t1p2-14-explain", source: "Cambridge 10 | T1-P2 14", prompt: "explain", answer: "take you through" },
    { id: "cam10-t1p2-16-compulsory", source: "Cambridge 10 | T1-P2 16", prompt: "compulsory", answer: "must" },
    { id: "cam10-t1p2-18-priority", source: "Cambridge 10 | T1-P2 18", prompt: "priority", answer: "preference" },
    { id: "cam10-t1p3-23-switch-it-on", source: "Cambridge 10 | T1-P3 23", prompt: "switch it on", answer: "start" },
    { id: "cam10-t1p3-24-change-back-to", source: "Cambridge 10 | T1-P3 24", prompt: "change back to", answer: "revert to" },
    { id: "cam10-t1p3-25-be-used", source: "Cambridge 10 | T1-P3 25", prompt: "be used", answer: "be used again and again" },
    { id: "cam10-t1p3-28-problem", source: "Cambridge 10 | T1-P3 28", prompt: "problem", answer: "difficulty" },
    { id: "cam10-t1p4-31-uncommon", source: "Cambridge 10 | T1-P4 31", prompt: "uncommon", answer: "special" },
    { id: "cam10-t1p4-32-unusual", source: "Cambridge 10 | T1-P4 32", prompt: "unusual", answer: "special" },
    { id: "cam10-t1p4-34-stop", source: "Cambridge 10 | T1-P4 34", prompt: "stop", answer: "prevent" },
    { id: "cam10-t1p4-35-a-small-number-of", source: "Cambridge 10 | T1-P4 35", prompt: "a small number of", answer: "a few" },
    { id: "cam10-t1p4-36-construction", source: "Cambridge 10 | T1-P4 36", prompt: "construction", answer: "build" },
    { id: "cam10-t1p4-37-unrestricted", source: "Cambridge 10 | T1-P4 37", prompt: "unrestricted", answer: "no legal limit" },
    { id: "cam10-t1p4-39-maintenance", source: "Cambridge 10 | T1-P4 39", prompt: "maintenance", answer: "maintain" },
    { id: "cam10-t2p1-4-occupation", source: "Cambridge 10 | T2-P1 4", prompt: "occupation", answer: "job" },
    { id: "cam10-t2p2-15-animal", source: "Cambridge 10 | T2-P2 15", prompt: "animal", answer: "fauna" },
    { id: "cam10-t2p2-15-local", source: "Cambridge 10 | T2-P2 15", prompt: "local", answer: "native to the region" },
    { id: "cam10-t2p2-17-jewels", source: "Cambridge 10 | T2-P2 17", prompt: "jewels", answer: "precious stones" },
    { id: "cam10-t2p2-18-space-travel", source: "Cambridge 10 | T2-P2 18", prompt: "space travel", answer: "international space station" },
    { id: "cam10-t2p2-20-waterways", source: "Cambridge 10 | T2-P2 20", prompt: "waterways", answer: "rivers" },
    { id: "cam10-t2p3-21-interested-in", source: "Cambridge 10 | T2-P3 21", prompt: "interested in", answer: "passion for" },
    { id: "cam10-t2p3-24-extreme-environment", source: "Cambridge 10 | T2-P3 24", prompt: "extreme environment", answer: "harsh weather conditions" },
    { id: "cam10-t2p3-26-test-a-new-theory", source: "Cambridge 10 | T2-P3 26", prompt: "test a new theory", answer: "try out his idea" },
    { id: "cam10-t2p3-28-stone-statue", source: "Cambridge 10 | T2-P3 28", prompt: "stone statue", answer: "stone carving" },
    { id: "cam10-t2p3-30-out-of-date", source: "Cambridge 10 | T2-P3 30", prompt: "out of date", answer: "old-fashioned" },
    { id: "cam10-t2p4-32-large-global-companies", source: "Cambridge 10 | T2-P4 32", prompt: "large global companies", answer: "major global corporations" },
    { id: "cam10-t2p4-33-countries", source: "Cambridge 10 | T2-P4 33", prompt: "countries", answer: "economies" },
    { id: "cam10-t2p4-34-discussions", source: "Cambridge 10 | T2-P4 34", prompt: "discussions", answer: "consult" },
    { id: "cam10-t2p4-36-particular", source: "Cambridge 10 | T2-P4 36", prompt: "particular", answer: "specific" },
    { id: "cam10-t2p4-39-senior-roles", source: "Cambridge 10 | T2-P4 39", prompt: "senior roles", answer: "senior management positions" },
    { id: "cam10-t3p2-11-help-finance", source: "Cambridge 10 | T3-P2 11", prompt: "help finance", answer: "use its money to support" },
    { id: "cam10-t3p2-16-not-been-seen", source: "Cambridge 10 | T3-P2 16", prompt: "not been seen", answer: "elusive" },
    { id: "cam10-t3p2-18-energetic", source: "Cambridge 10 | T3-P2 18", prompt: "energetic", answer: "a lot of energy" },
    { id: "cam10-t3p2-19-newest", source: "Cambridge 10 | T3-P2 19", prompt: "newest", answer: "latest" },
    { id: "cam10-t3p3-21-imagine", source: "Cambridge 10 | T3-P3 21", prompt: "imagine", answer: "visualize" },
    { id: "cam10-t3p3-23-clear-guidelines", source: "Cambridge 10 | T3-P3 23", prompt: "clear guidelines", answer: "exactly what to do" },
    { id: "cam10-t3p3-24-changing", source: "Cambridge 10 | T3-P3 24", prompt: "changing", answer: "shifting" },
    { id: "cam10-t3p3-27-relevant", source: "Cambridge 10 | T3-P3 27", prompt: "relevant", answer: "fit in" },
    { id: "cam10-t3p3-30-plan-for", source: "Cambridge 10 | T3-P3 30", prompt: "plan for", answer: "make arrangements for" },
    { id: "cam10-t3p4-31-focus-on", source: "Cambridge 10 | T3-P4 31", prompt: "focus on", answer: "emphasize" },
    { id: "cam10-t3p4-32-comes-from", source: "Cambridge 10 | T3-P4 32", prompt: "comes from", answer: "is connected to" },
    { id: "cam10-t3p4-36-behavior", source: "Cambridge 10 | T3-P4 36", prompt: "behavior", answer: "behave" },
    { id: "cam10-t3p4-38-clear", source: "Cambridge 10 | T3-P4 38", prompt: "clear", answer: "definitive" },
    { id: "cam10-t4p1-3-behind", source: "Cambridge 10 | T4-P1 3", prompt: "behind", answer: "at the back of" },
    { id: "cam10-t4p1-9-approximately", source: "Cambridge 10 | T4-P1 9", prompt: "approximately", answer: "about" },
    { id: "cam10-t4p2-12-increase-in-demand", source: "Cambridge 10 | T4-P2 12", prompt: "increase in demand", answer: "a tremendous need" },
    { id: "cam10-t4p2-13-shortage", source: "Cambridge 10 | T4-P2 13", prompt: "shortage", answer: "not enough" },
    { id: "cam10-t4p2-15-rebuild", source: "Cambridge 10 | T4-P2 15", prompt: "rebuild", answer: "reconstruct" },
    { id: "cam10-t4p2-18-exhibition", source: "Cambridge 10 | T4-P2 18", prompt: "exhibition", answer: "display" },
    { id: "cam10-t4p3-23-immediate", source: "Cambridge 10 | T4-P3 23", prompt: "immediate", answer: "straight away" },
    { id: "cam10-t4p3-24-improve", source: "Cambridge 10 | T4-P3 24", prompt: "improve", answer: "enhance" },
    { id: "cam10-t4p3-27-internet", source: "Cambridge 10 | T4-P3 27", prompt: "Internet", answer: "websites" },
    { id: "cam10-t4p4-31-misunderstand", source: "Cambridge 10 | T4-P4 31", prompt: "misunderstand", answer: "get the wrong idea" },
    { id: "cam10-t4p4-33-continue", source: "Cambridge 10 | T4-P4 33", prompt: "continue", answer: "plough ahead" },
    { id: "cam10-t4p4-37-affordable", source: "Cambridge 10 | T4-P4 37", prompt: "affordable", answer: "economical" },

    { id: "cam11-t1p1-6-arrange", source: "Cambridge 11 | T1-P1 6", prompt: "arrange", answer: "make the arrangements" },
    { id: "cam11-t1p2-11-harm", source: "Cambridge 11 | T1-P2 11", prompt: "harm", answer: "frighten or injure" },
    { id: "cam11-t1p2-12-not-touch", source: "Cambridge 11 | T1-P2 12", prompt: "not touch", answer: "stay at a safe distance" },
    { id: "cam11-t1p3-22-aim", source: "Cambridge 11 | T1-P3 22", prompt: "aim", answer: "what the researchers wanted to find out" },
    { id: "cam11-t1p3-24-important", source: "Cambridge 11 | T1-P3 24", prompt: "important", answer: "significant" },
    { id: "cam11-t1p3-25-reduce-stress", source: "Cambridge 11 | T1-P3 25", prompt: "reduce stress", answer: "relax" },
    { id: "cam11-t1p3-26-surprised", source: "Cambridge 11 | T1-P3 26", prompt: "surprised", answer: "hadn't expected" },
    { id: "cam11-t1p4-34-sufficient", source: "Cambridge 11 | T1-P4 34", prompt: "sufficient", answer: "enough" },
    { id: "cam11-t1p4-36-under", source: "Cambridge 11 | T1-P4 36", prompt: "under", answer: "below" },
    { id: "cam11-t1p4-39-establish", source: "Cambridge 11 | T1-P4 39", prompt: "establish", answer: "create" },
    { id: "cam11-t2p1-1-during-the-week", source: "Cambridge 11 | T2-P1 1", prompt: "during the week", answer: "from Monday to Friday" },
    { id: "cam11-t2p1-7-interested-in", source: "Cambridge 11 | T2-P1 7", prompt: "interested in", answer: "keen on" },
    { id: "cam11-t2p2-12-outside", source: "Cambridge 11 | T2-P2 12", prompt: "outside", answer: "exterior" },
    { id: "cam11-t2p3-21-where-live", source: "Cambridge 11 | T2-P3 21", prompt: "where ... live", answer: "habitats" },
    { id: "cam11-t2p3-24-simple", source: "Cambridge 11 | T2-P3 24", prompt: "simple", answer: "straightforward" },
    { id: "cam11-t2p3-26-photos", source: "Cambridge 11 | T2-P3 26", prompt: "photos", answer: "pictures" },
    { id: "cam11-t2p3-27-lack-of-water", source: "Cambridge 11 | T2-P3 27", prompt: "lack of water", answer: "dry out" },
    { id: "cam11-t2p3-28-high-temperatures", source: "Cambridge 11 | T2-P3 28", prompt: "high temperatures", answer: "too hot" },
    { id: "cam11-t2p4-32-disused", source: "Cambridge 11 | T2-P4 32", prompt: "disused", answer: "run-down / empty" },
    { id: "cam11-t2p4-36-large", source: "Cambridge 11 | T2-P4 36", prompt: "large", answer: "huge" },
    { id: "cam11-t2p4-37-made-of", source: "Cambridge 11 | T2-P4 37", prompt: "made of", answer: "constructed from" },
    { id: "cam11-t3p1-3-most", source: "Cambridge 11 | T3-P1 3", prompt: "most", answer: "majority" },
    { id: "cam11-t3p1-5-begin", source: "Cambridge 11 | T3-P1 5", prompt: "begin", answer: "start" },
    { id: "cam11-t3p1-7-rare", source: "Cambridge 11 | T3-P1 7", prompt: "rare", answer: "unusual" },
  ];

  root.SYNONYM_DATA = SYNONYM_DATA;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = SYNONYM_DATA;
  }
})(typeof window !== "undefined" ? window : globalThis);
