;(function (root) {
  const SYNONYM_DATA = [
    { id: "cam10-t1p2-12-improve", source: "Cambridge 10 | T1-P2 12", prompt: "improve", answer: "refurbish", chinese: "改善；翻新；整修" },
    { id: "cam10-t1p2-14-explain", source: "Cambridge 10 | T1-P2 14", prompt: "explain", answer: "take you through", chinese: "解释；带你详细讲解" },
    { id: "cam10-t1p2-16-compulsory", source: "Cambridge 10 | T1-P2 16", prompt: "compulsory", answer: "must", chinese: "强制的；必须" },
    { id: "cam10-t1p2-18-priority", source: "Cambridge 10 | T1-P2 18", prompt: "priority", answer: "preference", chinese: "优先考虑；偏好" },
    { id: "cam10-t1p3-23-switch-it-on", source: "Cambridge 10 | T1-P3 23", prompt: "switch it on", answer: "start", chinese: "打开；启动" },
    { id: "cam10-t1p3-24-change-back-to", source: "Cambridge 10 | T1-P3 24", prompt: "change back to", answer: "revert to", chinese: "改回；恢复到" },
    { id: "cam10-t1p3-25-be-used", source: "Cambridge 10 | T1-P3 25", prompt: "be used", answer: "be used again and again", chinese: "被使用；反复使用" },
    { id: "cam10-t1p3-28-problem", source: "Cambridge 10 | T1-P3 28", prompt: "problem", answer: "difficulty", chinese: "问题；困难" },
    { id: "cam10-t1p4-31-uncommon", source: "Cambridge 10 | T1-P4 31", prompt: "uncommon", answer: "special", chinese: "不常见的；特别的" },
    { id: "cam10-t1p4-32-unusual", source: "Cambridge 10 | T1-P4 32", prompt: "unusual", answer: "special", chinese: "不寻常的；特别的" },
    { id: "cam10-t1p4-34-stop", source: "Cambridge 10 | T1-P4 34", prompt: "stop", answer: "prevent", chinese: "停止；阻止" },
    { id: "cam10-t1p4-35-a-small-number-of", source: "Cambridge 10 | T1-P4 35", prompt: "a small number of", answer: "a few", chinese: "少量的；几个" },
    { id: "cam10-t1p4-36-construction", source: "Cambridge 10 | T1-P4 36", prompt: "construction", answer: "build", chinese: "建设；建造" },
    { id: "cam10-t1p4-37-unrestricted", source: "Cambridge 10 | T1-P4 37", prompt: "unrestricted", answer: "no legal limit", chinese: "不受限制的；没有法律限制" },
    { id: "cam10-t1p4-39-maintenance", source: "Cambridge 10 | T1-P4 39", prompt: "maintenance", answer: "maintain", chinese: "维护；保养" },
    { id: "cam10-t2p1-4-occupation", source: "Cambridge 10 | T2-P1 4", prompt: "occupation", answer: "job", chinese: "职业；工作" },
    { id: "cam10-t2p2-15-animal", source: "Cambridge 10 | T2-P2 15", prompt: "animal", answer: "fauna", chinese: "动物；动物群" },
    { id: "cam10-t2p2-15-local", source: "Cambridge 10 | T2-P2 15", prompt: "local", answer: "native to the region", chinese: "本地的；该地区原生的" },
    { id: "cam10-t2p2-17-jewels", source: "Cambridge 10 | T2-P2 17", prompt: "jewels", answer: "precious stones", chinese: "珠宝；宝石" },
    { id: "cam10-t2p2-18-space-travel", source: "Cambridge 10 | T2-P2 18", prompt: "space travel", answer: "international space station", chinese: "太空旅行；国际空间站" },
    { id: "cam10-t2p2-20-waterways", source: "Cambridge 10 | T2-P2 20", prompt: "waterways", answer: "rivers", chinese: "水道；河流" },
    { id: "cam10-t2p3-21-interested-in", source: "Cambridge 10 | T2-P3 21", prompt: "interested in", answer: "passion for", chinese: "对…感兴趣；热爱" },
    { id: "cam10-t2p3-24-extreme-environment", source: "Cambridge 10 | T2-P3 24", prompt: "extreme environment", answer: "harsh weather conditions", chinese: "极端环境；恶劣天气条件" },
    { id: "cam10-t2p3-26-test-a-new-theory", source: "Cambridge 10 | T2-P3 26", prompt: "test a new theory", answer: "try out his idea", chinese: "检验新理论；试验他的想法" },
    { id: "cam10-t2p3-28-stone-statue", source: "Cambridge 10 | T2-P3 28", prompt: "stone statue", answer: "stone carving", chinese: "石像；石雕" },
    { id: "cam10-t2p3-30-out-of-date", source: "Cambridge 10 | T2-P3 30", prompt: "out of date", answer: "old-fashioned", chinese: "过时的；老式的" },
    { id: "cam10-t2p4-32-large-global-companies", source: "Cambridge 10 | T2-P4 32", prompt: "large global companies", answer: "major global corporations", chinese: "大型跨国公司；主要全球企业" },
    { id: "cam10-t2p4-33-countries", source: "Cambridge 10 | T2-P4 33", prompt: "countries", answer: "economies", chinese: "国家；经济体" },
    { id: "cam10-t2p4-34-discussions", source: "Cambridge 10 | T2-P4 34", prompt: "discussions", answer: "consult", chinese: "讨论；咨询" },
    { id: "cam10-t2p4-36-particular", source: "Cambridge 10 | T2-P4 36", prompt: "particular", answer: "specific", chinese: "特定的；具体的" },
    { id: "cam10-t2p4-39-senior-roles", source: "Cambridge 10 | T2-P4 39", prompt: "senior roles", answer: "senior management positions", chinese: "高级职位；高层管理岗位" },
    { id: "cam10-t3p2-11-help-finance", source: "Cambridge 10 | T3-P2 11", prompt: "help finance", answer: "use its money to support", chinese: "资助；用资金支持" },
    { id: "cam10-t3p2-16-not-been-seen", source: "Cambridge 10 | T3-P2 16", prompt: "not been seen", answer: "elusive", chinese: "未被看到；难以发现的" },
    { id: "cam10-t3p2-18-energetic", source: "Cambridge 10 | T3-P2 18", prompt: "energetic", answer: "a lot of energy", chinese: "精力充沛的；很有活力" },
    { id: "cam10-t3p2-19-newest", source: "Cambridge 10 | T3-P2 19", prompt: "newest", answer: "latest", chinese: "最新的；最近的" },
    { id: "cam10-t3p3-21-imagine", source: "Cambridge 10 | T3-P3 21", prompt: "imagine", answer: "visualize", chinese: "想象；在脑中形成画面" },
    { id: "cam10-t3p3-23-clear-guidelines", source: "Cambridge 10 | T3-P3 23", prompt: "clear guidelines", answer: "exactly what to do", chinese: "明确指导；确切该做什么" },
    { id: "cam10-t3p3-24-changing", source: "Cambridge 10 | T3-P3 24", prompt: "changing", answer: "shifting", chinese: "变化的；转变中的" },
    { id: "cam10-t3p3-27-relevant", source: "Cambridge 10 | T3-P3 27", prompt: "relevant", answer: "fit in", chinese: "相关的；适合；契合" },
    { id: "cam10-t3p3-30-plan-for", source: "Cambridge 10 | T3-P3 30", prompt: "plan for", answer: "make arrangements for", chinese: "为…做计划；为…做安排" },
    { id: "cam10-t3p4-31-focus-on", source: "Cambridge 10 | T3-P4 31", prompt: "focus on", answer: "emphasize", chinese: "专注于；强调" },
    { id: "cam10-t3p4-32-comes-from", source: "Cambridge 10 | T3-P4 32", prompt: "comes from", answer: "is connected to", chinese: "来自；与…有关联" },
    { id: "cam10-t3p4-36-behavior", source: "Cambridge 10 | T3-P4 36", prompt: "behavior", answer: "behave", chinese: "行为；表现" },
    { id: "cam10-t3p4-38-clear", source: "Cambridge 10 | T3-P4 38", prompt: "clear", answer: "definitive", chinese: "清晰的；明确无疑的" },
    { id: "cam10-t4p1-3-behind", source: "Cambridge 10 | T4-P1 3", prompt: "behind", answer: "at the back of", chinese: "在后面；在…后方" },
    { id: "cam10-t4p1-9-approximately", source: "Cambridge 10 | T4-P1 9", prompt: "approximately", answer: "about", chinese: "大约；左右" },
    { id: "cam10-t4p2-12-increase-in-demand", source: "Cambridge 10 | T4-P2 12", prompt: "increase in demand", answer: "a tremendous need", chinese: "需求增加；巨大的需求" },
    { id: "cam10-t4p2-13-shortage", source: "Cambridge 10 | T4-P2 13", prompt: "shortage", answer: "not enough", chinese: "短缺；不够" },
    { id: "cam10-t4p2-15-rebuild", source: "Cambridge 10 | T4-P2 15", prompt: "rebuild", answer: "reconstruct", chinese: "重建；重新修建" },
    { id: "cam10-t4p2-18-exhibition", source: "Cambridge 10 | T4-P2 18", prompt: "exhibition", answer: "display", chinese: "展览；展示" },
    { id: "cam10-t4p3-23-immediate", source: "Cambridge 10 | T4-P3 23", prompt: "immediate", answer: "straight away", chinese: "立即的；马上" },
    { id: "cam10-t4p3-24-improve", source: "Cambridge 10 | T4-P3 24", prompt: "improve", answer: "enhance", chinese: "提升；增强" },
    { id: "cam10-t4p3-27-internet", source: "Cambridge 10 | T4-P3 27", prompt: "Internet", answer: "websites", chinese: "互联网；网站" },
    { id: "cam10-t4p4-31-misunderstand", source: "Cambridge 10 | T4-P4 31", prompt: "misunderstand", answer: "get the wrong idea", chinese: "误解；理解错意思" },
    { id: "cam10-t4p4-33-continue", source: "Cambridge 10 | T4-P4 33", prompt: "continue", answer: "plough ahead", chinese: "继续；坚持推进" },
    { id: "cam10-t4p4-37-affordable", source: "Cambridge 10 | T4-P4 37", prompt: "affordable", answer: "economical", chinese: "负担得起的；经济实惠的" },

    { id: "cam11-t1p1-6-arrange", source: "Cambridge 11 | T1-P1 6", prompt: "arrange", answer: "make the arrangements", chinese: "安排；做好安排" },
    { id: "cam11-t1p2-11-harm", source: "Cambridge 11 | T1-P2 11", prompt: "harm", answer: "frighten or injure", chinese: "伤害；使受惊或受伤" },
    { id: "cam11-t1p2-12-not-touch", source: "Cambridge 11 | T1-P2 12", prompt: "not touch", answer: "stay at a safe distance", chinese: "不要碰；保持安全距离" },
    { id: "cam11-t1p3-22-aim", source: "Cambridge 11 | T1-P3 22", prompt: "aim", answer: "what the researchers wanted to find out", chinese: "目标；研究者想弄清的内容" },
    { id: "cam11-t1p3-24-important", source: "Cambridge 11 | T1-P3 24", prompt: "important", answer: "significant", chinese: "重要的；显著的" },
    { id: "cam11-t1p3-25-reduce-stress", source: "Cambridge 11 | T1-P3 25", prompt: "reduce stress", answer: "relax", chinese: "减压；放松" },
    { id: "cam11-t1p3-26-surprised", source: "Cambridge 11 | T1-P3 26", prompt: "surprised", answer: "hadn't expected", chinese: "惊讶的；没预料到" },
    { id: "cam11-t1p4-34-sufficient", source: "Cambridge 11 | T1-P4 34", prompt: "sufficient", answer: "enough", chinese: "充足的；足够的" },
    { id: "cam11-t1p4-36-under", source: "Cambridge 11 | T1-P4 36", prompt: "under", answer: "below", chinese: "在下面；低于" },
    { id: "cam11-t1p4-39-establish", source: "Cambridge 11 | T1-P4 39", prompt: "establish", answer: "create", chinese: "建立；创建" },
    { id: "cam11-t2p1-1-during-the-week", source: "Cambridge 11 | T2-P1 1", prompt: "during the week", answer: "from Monday to Friday", chinese: "工作日；从周一到周五" },
    { id: "cam11-t2p1-7-interested-in", source: "Cambridge 11 | T2-P1 7", prompt: "interested in", answer: "keen on", chinese: "感兴趣；热衷于" },
    { id: "cam11-t2p2-12-outside", source: "Cambridge 11 | T2-P2 12", prompt: "outside", answer: "exterior", chinese: "外面；外部" },
    { id: "cam11-t2p3-21-where-live", source: "Cambridge 11 | T2-P3 21", prompt: "where ... live", answer: "habitats", chinese: "生活在哪里；栖息地" },
    { id: "cam11-t2p3-24-simple", source: "Cambridge 11 | T2-P3 24", prompt: "simple", answer: "straightforward", chinese: "简单的；直接易懂的" },
    { id: "cam11-t2p3-26-photos", source: "Cambridge 11 | T2-P3 26", prompt: "photos", answer: "pictures", chinese: "照片；图片" },
    { id: "cam11-t2p3-27-lack-of-water", source: "Cambridge 11 | T2-P3 27", prompt: "lack of water", answer: "dry out", chinese: "缺水；干涸" },
    { id: "cam11-t2p3-28-high-temperatures", source: "Cambridge 11 | T2-P3 28", prompt: "high temperatures", answer: "too hot", chinese: "高温；太热" },
    { id: "cam11-t2p4-32-disused", source: "Cambridge 11 | T2-P4 32", prompt: "disused", answer: "run-down / empty", chinese: "废弃的；破旧或空置的" },
    { id: "cam11-t2p4-36-large", source: "Cambridge 11 | T2-P4 36", prompt: "large", answer: "huge", chinese: "大的；巨大的" },
    { id: "cam11-t2p4-37-made-of", source: "Cambridge 11 | T2-P4 37", prompt: "made of", answer: "constructed from", chinese: "由…制成；由…建成" },
    { id: "cam11-t3p1-3-most", source: "Cambridge 11 | T3-P1 3", prompt: "most", answer: "majority", chinese: "大多数；多数人" },
    { id: "cam11-t3p1-5-begin", source: "Cambridge 11 | T3-P1 5", prompt: "begin", answer: "start", chinese: "开始；启动" },
    { id: "cam11-t3p1-7-rare", source: "Cambridge 11 | T3-P1 7", prompt: "rare", answer: "unusual", chinese: "稀少的；不寻常的" }
  ];

  root.SYNONYM_DATA = SYNONYM_DATA;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = SYNONYM_DATA;
  }
})(typeof window !== "undefined" ? window : globalThis);
